### ISSUE TITLE
User Story 3: Location, contact details and opening hours (must-have)

### ISSUE THREAD

**Issue by tbuchan1997** [tbuchan1997/boardwalk-games#3]
**User Story:** 

As a Prospective Customer, I need to find essential information such as location, contact details, and opening hours clearly and concisely, so I can easily plan my visit or get in touch with the café.

**Acceptance Criteria**

- [x]     The website contains a dedicated section for location, contact details, and opening hours.
- [x]     This section is clearly visible and accessible from all parts of the website.

**Tasks**

- [x]     TDesign and place a section for location, contact details, and opening hours using information provided by the client.
- [x]     TEnsure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
