### ISSUE TITLE
Feature 1: Selected board games displayed on a separate Game Library page - must-have

### ISSUE THREAD

**Issue by tbuchan1997** [tbuchan1997/boardwalk-games#8]
**User Story:** 

As a Board Game Enthusiast, I want to explore a selection of featured board games on the website, so I can discover new games and decide which ones I might be interested in trying or buying.

**Acceptance Criteria**

- [x]     The website has a separate page for the list of board games.
- [x]     The game library page utilises the Bootstrap grid and card components for consistency in layout and responsiveness.
- [x]     Each card states the relevant game title, image, descriptions, number of players and age range.

**Tasks**

- [x]     Create a responsive Game Library page featuring a handful of selected games and their relevant details.
