### ISSUE TITLE
Feature 2: Form to reserve a board game on the Game Library page -  should-have

### ISSUE THREAD

**Issue by tbuchan1997** [tbuchan1997/boardwalk-games#9]
**User Story:** 

As a Board Game Enthusiast, I want to reserve a board game from the list of available games, so I can ensure it's available for me when I visit the shop.

**Acceptance Criteria**

- [x]     A reservation form is available on the Game Library page.
- [x]     The user can fill out their selected game, name, contact information, and preferred date for the reservation.

**Tasks**

- [x]     Create a reservation form with fields for the user's name, contact information, preferred date and select which game they want to reserve.
